"""Export the deterministic demo as Hugging Face-ready dataset and model repos.

This exporter intentionally accepts only the synthetic quick-start artifacts. It
does not download, package, or redistribute market data.

Example
-------
python scripts/export_huggingface_artifacts.py \
  --artifacts-dir artifacts/small \
  --config configs/small.yaml \
  --output-dir artifacts/huggingface
"""
from __future__ import annotations

import argparse
import csv
import gzip
import hashlib
import io
import json
import shutil
import subprocess
from pathlib import Path
from typing import Any, Sequence

import torch
import yaml


DATASET_REPO_NAME = "ml-quant-trading-synthetic"
MODEL_REPO_NAME = "ml-quant-trading-synthetic-mlp"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _write_json(path: Path, payload: Any) -> None:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _source_commit() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], text=True, stderr=subprocess.DEVNULL
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def _require_empty_or_forced(path: Path, *, force: bool) -> None:
    if path.exists() and any(path.iterdir()) and not force:
        raise FileExistsError(f"{path} is not empty; pass --force to replace generated files")
    path.mkdir(parents=True, exist_ok=True)


def _date_text(value: Any) -> str:
    if hasattr(value, "isoformat"):
        return value.isoformat()
    return str(value)


def _write_dataset_csv(panel: dict[str, Any], path: Path) -> int:
    required = ("dates", "stocks", "open", "high", "low", "close", "volume", "vwap", "mask")
    missing = [key for key in required if key not in panel]
    if missing:
        raise ValueError(f"panel artifact is missing keys: {', '.join(missing)}")

    dates = panel["dates"]
    stocks = panel["stocks"]
    tensors = {key: torch.as_tensor(panel[key]).cpu() for key in required[2:]}
    shape = tensors["close"].shape
    if len(shape) != 2 or shape != (len(dates), len(stocks)):
        raise ValueError("panel tensors must have shape [n_dates, n_assets]")
    if any(tensor.shape != shape for tensor in tensors.values()):
        raise ValueError("all panel tensors must share the close tensor shape")

    path.parent.mkdir(parents=True, exist_ok=True)
    rows = 0
    with path.open("wb") as raw:
        with gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0) as zipped:
            with io.TextIOWrapper(zipped, encoding="utf-8", newline="") as text:
                writer = csv.writer(text, lineterminator="\n")
                writer.writerow(
                    [
                        "date",
                        "asset_id",
                        "open",
                        "high",
                        "low",
                        "close",
                        "volume",
                        "vwap",
                        "tradable",
                    ]
                )
                for date_index, date in enumerate(dates):
                    for asset_index, asset in enumerate(stocks):
                        writer.writerow(
                            [
                                _date_text(date),
                                str(asset),
                                *(f"{float(tensors[key][date_index, asset_index]):.9g}" for key in required[2:8]),
                                int(bool(tensors["mask"][date_index, asset_index])),
                            ]
                        )
                        rows += 1
    return rows


def _dataset_card(
    *, namespace: str, rows: int, n_dates: int, n_assets: int, commit: str, checksum: str
) -> str:
    size_category = "10K<n<100K" if rows < 100_000 else "100K<n<1M"
    return f"""---
license: mit
language:
- en
pretty_name: ml-quant-trading deterministic synthetic OHLCV panel
size_categories:
- {size_category}
task_categories:
- time-series-forecasting
tags:
- finance
- synthetic
- quantitative-trading
- reproducibility
- pytorch
configs:
- config_name: default
  data_files:
  - split: train
    path: data/synthetic_ohlcv.csv.gz
---

# ml-quant-trading deterministic synthetic panel

This dataset is the zero-account smoke-test panel generated by
[`ml-quant-trading`](https://github.com/initial-d/ml-quant-trading). It contains
**no real instruments, proprietary market data, or investment signals**.

## Dataset structure

- Rows: **{rows:,}** (`{n_dates}` dates × `{n_assets}` synthetic assets)
- Columns: `date`, `asset_id`, OHLCV, `vwap`, and `tradable`
- Generator commit: [`{commit}`](https://github.com/initial-d/ml-quant-trading/commit/{commit})
- Data SHA-256: `{checksum}`

Asset identifiers are synthetic labels and do not map to listed securities.
Prices come from the repository's deterministic GBM-style generator. Missing and
untradable cells are simulated to exercise masks and pipeline behavior.

## Load

```python
from datasets import load_dataset

dataset = load_dataset("{namespace}/{DATASET_REPO_NAME}")
print(dataset["train"][0])
```

## Intended use

- test installation and data-loading paths;
- reproduce the public synthetic demo;
- exercise factor, model, portfolio, and backtest code without market-data access;
- build CI or teaching examples.

## Not intended for

- estimating real-market performance;
- training or evaluating a deployable trading strategy;
- mapping synthetic asset IDs to real securities;
- investment decisions.

Regenerate the bundle from the source repository:

```bash
mlquant demo
python scripts/export_huggingface_artifacts.py
```

See the project's [Research Card](https://github.com/initial-d/ml-quant-trading/blob/main/docs/research_card.md)
and [Reality Check](https://github.com/initial-d/ml-quant-trading/blob/main/docs/reality_check.md).
"""


def _model_card(
    *, namespace: str, commit: str, checkpoint_sha: str, in_dim: int, hidden: int
) -> str:
    return f"""---
license: mit
library_name: pytorch
pipeline_tag: tabular-regression
datasets:
- {namespace}/{DATASET_REPO_NAME}
tags:
- finance
- synthetic
- quantitative-trading
- reproducibility
- pytorch
---

# ml-quant-trading synthetic MLP smoke-test checkpoint

This is the small `MLPRegressor` checkpoint produced by the deterministic
`mlquant demo` pipeline. It is published to make installation and inference
paths reproducible — **not as a market model or investment signal**.

## Model details

- Architecture: three-layer MLP with GELU and dropout
- Input dimensions: `{in_dim}` factor values
- Hidden width: `{hidden}`
- Output: one synthetic next-period return score per asset-date
- Training data: [`{namespace}/{DATASET_REPO_NAME}`](https://huggingface.co/datasets/{namespace}/{DATASET_REPO_NAME})
- Source commit: [`{commit}`](https://github.com/initial-d/ml-quant-trading/commit/{commit})
- Checkpoint SHA-256: `{checkpoint_sha}`

The companion `feature_names.json`, `config.json`, `source_config.yaml`, and
`metrics.json` files define the input order, architecture, generator settings,
and synthetic smoke-test output.

## Load

```python
import json
import torch
from huggingface_hub import hf_hub_download
from mlquant.models.nets import MLPRegressor

repo_id = "{namespace}/{MODEL_REPO_NAME}"
config_path = hf_hub_download(repo_id, "config.json")
weights_path = hf_hub_download(repo_id, "pytorch_model.bin")

config = json.load(open(config_path))
model = MLPRegressor(
    in_dim=config["in_dim"],
    hidden=config["hidden"],
    dropout=config["dropout"],
)
model.load_state_dict(torch.load(weights_path, map_location="cpu", weights_only=True))
model.eval()
```

## Limitations

- The checkpoint was trained only on deterministic synthetic data.
- Synthetic smoke-test metrics are not evidence of out-of-sample alpha.
- Factor values must use the exact order in `feature_names.json`.
- The package is research software, not a live-trading system.

See the project's [Research Card](https://github.com/initial-d/ml-quant-trading/blob/main/docs/research_card.md)
and [Reality Check](https://github.com/initial-d/ml-quant-trading/blob/main/docs/reality_check.md).
"""


def export_bundle(
    *,
    artifacts_dir: Path,
    config_path: Path,
    output_dir: Path,
    namespace: str = "dddyym",
    source_commit: str | None = None,
    force: bool = False,
) -> dict[str, Any]:
    """Create two self-contained directories ready for Hugging Face upload."""
    panel_path = artifacts_dir / "panel.pt"
    features_path = artifacts_dir / "features.pt"
    checkpoint_path = artifacts_dir / "checkpoints" / "best.pt"
    summary_path = artifacts_dir / "summary.json"
    for required_path in (panel_path, features_path, checkpoint_path, summary_path, config_path):
        if not required_path.exists():
            raise FileNotFoundError(f"required demo artifact not found: {required_path}")

    config = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    if "synthetic" not in config:
        raise ValueError("only configs with a synthetic section can be exported")

    dataset_dir = output_dir / DATASET_REPO_NAME
    model_dir = output_dir / MODEL_REPO_NAME
    _require_empty_or_forced(dataset_dir, force=force)
    _require_empty_or_forced(model_dir, force=force)

    panel = torch.load(panel_path, map_location="cpu", weights_only=False)
    features = torch.load(features_path, map_location="cpu", weights_only=False)
    names: Sequence[str] = features.get("names", [])
    if not names:
        raise ValueError("features artifact does not contain factor names")

    commit = source_commit or _source_commit()
    data_path = dataset_dir / "data" / "synthetic_ohlcv.csv.gz"
    rows = _write_dataset_csv(panel, data_path)
    data_sha = _sha256(data_path)
    dataset_manifest = {
        "artifact_type": "synthetic_ohlcv_panel",
        "data_file": str(data_path.relative_to(dataset_dir)).replace("\\", "/"),
        "data_sha256": data_sha,
        "generator_commit": commit,
        "n_assets": len(panel["stocks"]),
        "n_dates": len(panel["dates"]),
        "rows": rows,
        "source": "deterministic synthetic generator; no market data",
    }
    _write_json(dataset_dir / "artifact_manifest.json", dataset_manifest)
    shutil.copy2(config_path, dataset_dir / "source_config.yaml")
    (dataset_dir / "README.md").write_text(
        _dataset_card(
            namespace=namespace,
            rows=rows,
            n_dates=len(panel["dates"]),
            n_assets=len(panel["stocks"]),
            commit=commit,
            checksum=data_sha,
        ),
        encoding="utf-8",
    )

    model_path = model_dir / "pytorch_model.bin"
    shutil.copy2(checkpoint_path, model_path)
    checkpoint_sha = _sha256(model_path)
    shutil.copy2(config_path, model_dir / "source_config.yaml")
    shutil.copy2(summary_path, model_dir / "metrics.json")
    _write_json(model_dir / "feature_names.json", list(names))
    model_config = {
        "architecture": "MLPRegressor",
        "dataset": f"{namespace}/{DATASET_REPO_NAME}",
        "dropout": 0.1,
        "hidden": int(config.get("hidden", 128)),
        "in_dim": len(names),
        "output_dim": 1,
        "source_commit": commit,
    }
    _write_json(model_dir / "config.json", model_config)
    _write_json(
        model_dir / "artifact_manifest.json",
        {
            "artifact_type": "synthetic_mlp_smoke_test",
            "checkpoint_file": "pytorch_model.bin",
            "checkpoint_sha256": checkpoint_sha,
            **model_config,
        },
    )
    (model_dir / "README.md").write_text(
        _model_card(
            namespace=namespace,
            commit=commit,
            checkpoint_sha=checkpoint_sha,
            in_dim=len(names),
            hidden=int(config.get("hidden", 128)),
        ),
        encoding="utf-8",
    )

    bundle_manifest = {
        "dataset_repo": f"{namespace}/{DATASET_REPO_NAME}",
        "dataset_rows": rows,
        "model_repo": f"{namespace}/{MODEL_REPO_NAME}",
        "output_dir": str(output_dir),
        "source_commit": commit,
    }
    output_dir.mkdir(parents=True, exist_ok=True)
    _write_json(output_dir / "bundle_manifest.json", bundle_manifest)
    return bundle_manifest


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--artifacts-dir", type=Path, default=Path("artifacts/small"))
    parser.add_argument("--config", type=Path, default=Path("configs/small.yaml"))
    parser.add_argument("--output-dir", type=Path, default=Path("artifacts/huggingface"))
    parser.add_argument("--namespace", default="dddyym")
    parser.add_argument("--source-commit")
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    manifest = export_bundle(
        artifacts_dir=args.artifacts_dir,
        config_path=args.config,
        output_dir=args.output_dir,
        namespace=args.namespace,
        source_commit=args.source_commit,
        force=args.force,
    )
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
